# Generated by Django 6.0.6 on 2026-06-13 19:33

import django.core.validators
import django.db.models.deletion
import inventario.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('meio_hospedagem', 'Meio de Hospedagem'), ('meio_alimentacao_bebida', 'Alimentação e Bebidas'), ('atrativo', 'Atrativo, Lazer e Entretenimento'), ('espaco_evento', 'Espaço para Eventos'), ('agencia_turismo', 'Agência/Operadora de Turismo'), ('organizador_evento', 'Organizador/Serviço p/ Eventos'), ('locadora_transporte', 'Locadora/Transporte Turístico'), ('artesanato', 'Artesanato e Comércio Diferenciado'), ('banco', 'Banco'), ('templo_religioso', 'Templo Religioso'), ('servico_saude', 'Serviço de Saúde'), ('servico_apoio', 'Serviço de Apoio ao Turista'), ('guia_turismo', 'Guia de Turismo'), ('rhc', 'RHC — Registro Habitacional Complementar'), ('grupo_folclorico', 'Grupo Folclórico/Parafolclórico'), ('taxi_aplicativo', 'Táxi, Mototáxi e Aplicativo')], db_index=True, editable=False, help_text='Discriminador do segmento — preenchido automaticamente pela filha.', max_length=40)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'registro do inventário',
                'verbose_name_plural': 'registros do inventário',
                'db_table': 'registro_inventario',
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('transferencia', 'Transferência Bancária')], max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'forma de pagamento',
                'verbose_name_plural': 'formas de pagamento',
                'db_table': 'pagamento',
            },
        ),
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escopo', models.CharField(choices=[('atrativos', 'Atrativos, Lazer e Entretenimento'), ('meio_hospedagem', 'Meios de Hospedagem'), ('alimentacao', 'Meios de Alimentação e Bebidas'), ('agencias', 'Agências e Operadoras de Turismo'), ('espacos_eventos', 'Espaços para Eventos'), ('organizadores', 'Organizadores e Serviços p/ Eventos'), ('artesanato', 'Artesanato e Comércio Diferenciado')], max_length=20)),
                ('nome', models.CharField(help_text='Agrupador/escopo do grupo.', max_length=120)),
                ('categoria', models.CharField(help_text='Opção/item do grupo.', max_length=255)),
                ('customizada', models.BooleanField(default=False, help_text='Criada dinamicamente ([Texto Dinâmico Customizado]).')),
            ],
            options={
                'verbose_name': 'característica',
                'verbose_name_plural': 'características',
                'db_table': 'caracteristica',
                'constraints': [models.UniqueConstraint(fields=('escopo', 'nome', 'categoria'), name='uq_caracteristica_escopo_nome_categoria')],
            },
        ),
        migrations.CreateModel(
            name='CaracteristicaValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escopo', models.CharField(choices=[('atrativos', 'Atrativos, Lazer e Entretenimento'), ('meio_hospedagem', 'Meios de Hospedagem'), ('alimentacao', 'Meios de Alimentação e Bebidas'), ('agencias', 'Agências e Operadoras de Turismo'), ('espacos_eventos', 'Espaços para Eventos'), ('organizadores', 'Organizadores e Serviços p/ Eventos'), ('artesanato', 'Artesanato e Comércio Diferenciado')], max_length=20)),
                ('nome', models.CharField(max_length=120)),
                ('categoria', models.CharField(max_length=255)),
                ('descricao', models.CharField(blank=True, help_text='Semântica/exemplo (coluna do doc de regras).', max_length=255)),
            ],
            options={
                'verbose_name': 'métrica (característica-valor)',
                'verbose_name_plural': 'métricas (característica-valor)',
                'db_table': 'caracteristica_valor',
                'constraints': [models.UniqueConstraint(fields=('escopo', 'nome', 'categoria'), name='uq_caracteristica_valor_escopo_nome_categoria')],
            },
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('registroinventario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventario.registroinventario')),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('razao_social', models.CharField(blank=True, max_length=255)),
                ('cnpj', models.CharField(blank=True, help_text='UNIQUE e NULO permitido: atrativos públicos não possuem CNPJ.', max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='CNPJ deve conter exatamente 14 dígitos numéricos, sem máscara.', regex='^\\d{14}$')])),
                ('quantidade', models.PositiveIntegerField(blank=True, help_text='Campo de contagem herdado da planilha original.', null=True)),
                ('cnae', models.CharField(blank=True, max_length=10)),
                ('site', models.URLField(blank=True)),
                ('horario_atendimento', models.CharField(blank=True, help_text='Horário geral. Templos: horários de missa/culto (Regra 2.3).', max_length=255)),
                ('classificacao', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name': 'estabelecimento',
                'verbose_name_plural': 'estabelecimentos',
                'db_table': 'estabelecimento',
                'ordering': ['nome_fantasia'],
            },
            bases=('inventario.registroinventario',),
        ),
        migrations.CreateModel(
            name='GuiaTurismo',
            fields=[
                ('registroinventario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventario.registroinventario')),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve conter exatamente 11 dígitos numéricos, sem máscara.', regex='^\\d{11}$')])),
                ('nome', models.CharField(max_length=255)),
                ('categoria', models.CharField(blank=True, max_length=120)),
                ('classificacao', models.CharField(blank=True, max_length=120)),
                ('quantidade', models.PositiveIntegerField(blank=True, null=True)),
                ('destinos_inteligentes', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'guia de turismo',
                'verbose_name_plural': 'guias de turismo',
                'db_table': 'guia_turismo',
            },
            bases=('inventario.registroinventario',),
        ),
        migrations.CreateModel(
            name='RHC',
            fields=[
                ('registroinventario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventario.registroinventario')),
                ('numeracao_rhc', models.CharField(max_length=30, unique=True)),
                ('tipo_imovel', models.CharField(choices=[('apartamento', 'Apartamento'), ('casa', 'Casa'), ('chale', 'Chalé'), ('condominio_temporada', 'Condomínio de temporada'), ('outros', 'Outros')], max_length=25)),
                ('denominacao_comercial', models.CharField(blank=True, max_length=255)),
                ('nome_proprietario', models.CharField(blank=True, max_length=255)),
                ('cpf_proprietario', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='CPF deve conter exatamente 11 dígitos numéricos, sem máscara.', regex='^\\d{11}$')])),
                ('data_renovacao', models.DateField(blank=True, null=True)),
                ('data_liberacao', models.DateField(blank=True, null=True)),
                ('data_entrada', models.DateField(blank=True, null=True)),
                ('numero_processo', models.CharField(blank=True, max_length=40)),
                ('acessibilidade_pcd', models.BooleanField(default=False)),
                ('quantidade_leitos', models.PositiveIntegerField(blank=True, null=True)),
                ('capacidade_maxima', models.PositiveIntegerField(blank=True, null=True)),
                ('quantidade', models.PositiveIntegerField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'RHC',
                'verbose_name_plural': 'RHCs',
                'db_table': 'rhc',
            },
            bases=('inventario.registroinventario',),
        ),
        migrations.CreateModel(
            name='TaxiAplicativo',
            fields=[
                ('registroinventario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventario.registroinventario')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do taxista')),
                ('empresa', models.CharField(blank=True, max_length=255)),
                ('qtde_pontos', models.PositiveIntegerField(blank=True, null=True)),
                ('qtde_veiculos', models.PositiveIntegerField(blank=True, null=True)),
                ('credencial_alvara', models.CharField(blank=True, max_length=60)),
                ('numero_registro', models.CharField(blank=True, max_length=60)),
                ('placa', models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator(message='Placa deve seguir o padrão Mercosul (ABC1D23) ou o anterior (ABC-1234).', regex='^([A-Z]{3}-?\\d{4}|[A-Z]{3}\\d[A-Z]\\d{2})$')])),
                ('ano_habilitacao', models.PositiveIntegerField(blank=True, null=True, validators=[inventario.models.validar_ano_habilitacao])),
            ],
            options={
                'verbose_name': 'táxi/mototáxi/aplicativo',
                'verbose_name_plural': 'táxis/mototáxis/aplicativos',
                'db_table': 'taxi_aplicativo',
            },
            bases=('inventario.registroinventario',),
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator(message='CEP deve conter 8 dígitos numéricos, sem hífen.', regex='^\\d{8}$')])),
                ('rua', models.CharField(blank=True, max_length=255)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('bairro', models.CharField(blank=True, max_length=120)),
                ('regiao', models.CharField(blank=True, max_length=120)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('registro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='inventario.registroinventario')),
            ],
            options={
                'verbose_name': 'endereço',
                'verbose_name_plural': 'endereços',
                'db_table': 'endereco',
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('cargo', models.CharField(blank=True, help_text='Ex.: Proprietário, Gerente, Recepção, Contato para pesquisas.', max_length=120)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='inventario.registroinventario')),
            ],
            options={
                'verbose_name': 'contato',
                'verbose_name_plural': 'contatos',
                'db_table': 'contato',
            },
        ),
        migrations.CreateModel(
            name='Cadastur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscricao', models.BooleanField(default=True, help_text='Inscrição ativa no Cadastur.')),
                ('numero', models.CharField(blank=True, max_length=30)),
                ('vencimento', models.DateField(blank=True, null=True)),
                ('registro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cadastur', to='inventario.registroinventario')),
            ],
            options={
                'verbose_name': 'registro Cadastur',
                'verbose_name_plural': 'registros Cadastur',
                'db_table': 'cadastur',
            },
        ),
        migrations.CreateModel(
            name='IndicadorODS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eixo', models.PositiveSmallIntegerField(help_text='Eixo do indicador (1 ou 2).')),
                ('ods', models.PositiveSmallIntegerField(help_text='Número do ODS (ex.: 3, 5, 7, 12).')),
                ('descricao', models.CharField(max_length=255)),
                ('natureza', models.CharField(choices=[('quali', 'Qualitativo (booleano — a linha existir = Sim)'), ('quant', 'Quantitativo (exige valor)')], max_length=5)),
            ],
            options={
                'verbose_name': 'indicador ODS',
                'verbose_name_plural': 'indicadores ODS',
                'db_table': 'indicador_ods',
                'constraints': [models.UniqueConstraint(fields=('eixo', 'ods', 'descricao'), name='uq_indicador_ods')],
            },
        ),
        migrations.CreateModel(
            name='AgenciaOperadoraTurismo',
            fields=[
                ('estabelecimento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventario.estabelecimento')),
                ('estacionamento', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True)),
                ('destinos_inteligentes', models.BooleanField(default=False)),
                ('inicio_atividade', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'agência/operadora de turismo',
                'verbose_name_plural': 'agências/operadoras de turismo',
                'db_table': 'agencia_operadora_turismo',
            },
            bases=('inventario.estabelecimento',),
        ),
        migrations.CreateModel(
            name='Artesanato',
            fields=[
                ('estabelecimento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventario.estabelecimento')),
                ('destino_inteligente', models.BooleanField(default=False)),
                ('inventario', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'artesanato e comércio diferenciado',
                'verbose_name_plural': 'artesanatos e comércios diferenciados',
                'db_table': 'artesanato',
            },
            bases=('inventario.estabelecimento',),
        ),
        migrations.CreateModel(
            name='AtrativoLazerEntretenimento',
            fields=[
                ('estabelecimento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventario.estabelecimento')),
                ('local', models.CharField(blank=True, choices=[('ponto_historico', 'Pontos Históricos'), ('publico', 'Atrativos Turísticos Públicos'), ('privado', 'Atrativos Turísticos Privados')], max_length=20)),
                ('tipo_atrativo', models.CharField(blank=True, choices=[('arq_historica', 'Arquitetura histórica'), ('arq_oficial', 'Arquitetura oficial'), ('areas_verdes', 'Espaços livres/áreas verdes'), ('outros_recreacao', 'Outros espaços de recreação'), ('instalacoes_esportivas', 'Instalações esportivas'), ('manifestacoes_fe', 'Manifestações de fé'), ('centro_cultural', 'Centro cultural'), ('atrativo_monumental', 'Atrativo monumental'), ('instalacao_cultural', 'Instalação cultural'), ('outros_equipamentos', 'Outros equipamentos turísticos'), ('espacos_diversao', 'Espaços de diversão'), ('parque_aquatico', 'Parque aquático'), ('parque_tematico', 'Parque temático/diversões/lazer/gastronômico')], max_length=30)),
                ('data_inicio_funcionamento', models.DateField(blank=True, null=True)),
                ('estacionamento', models.BooleanField(default=False)),
                ('informacoes_gerais', models.TextField(blank=True)),
                ('destaque', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'atrativo, lazer e entretenimento',
                'verbose_name_plural': 'atrativos, lazer e entretenimento',
                'db_table': 'atrativo_lazer_entretenimento',
            },
            bases=('inventario.estabelecimento',),
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('estabelecimento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventario.estabelecimento')),
                ('principais_servicos', models.TextField(blank=True)),
                ('caixas_fora_agencia', models.TextField(blank=True, verbose_name='Caixas eletrônicos fora da agência')),
            ],
            options={
                'verbose_name': 'banco',
                'verbose_name_plural': 'bancos',
                'db_table': 'banco',
            },
            bases=('inventario.estabelecimento',),
        ),
        migrations.CreateModel(
            name='EspacoEvento',
            fields=[
                ('estabelecimento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventario.estabelecimento')),
                ('outras_regras', models.TextField(blank=True)),
                ('descricao_espaco', models.TextField(blank=True)),
                ('observacao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'espaço para eventos',
                'verbose_name_plural': 'espaços para eventos',
                'db_table': 'espaco_evento',
            },
            bases=('inventario.estabelecimento',),
        ),
        migrations.CreateModel(
            name='LocadoraVeiculoTransporte',
            fields=[
                ('estabelecimento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventario.estabelecimento')),
                ('tipo_locadora', models.CharField(blank=True, choices=[('locadora', 'Locadora'), ('transportadora', 'Transportadora Turística')], max_length=15)),
                ('destinos_inteligentes', models.BooleanField(default=False)),
                ('acessibilidade', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'locadora/transporte turístico',
                'verbose_name_plural': 'locadoras/transportes turísticos',
                'db_table': 'locadora_veiculo_transporte',
            },
            bases=('inventario.estabelecimento',),
        ),
        migrations.CreateModel(
            name='MeioAlimentacaoBebida',
            fields=[
                ('estabelecimento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventario.estabelecimento')),
                ('inicio_atividade', models.DateField(blank=True, null=True)),
                ('estacionamento', models.BooleanField(default=False)),
                ('especificacao_gastronomia', models.TextField(blank=True)),
                ('observacao', models.TextField(blank=True)),
                ('parque', models.BooleanField(default=False, help_text='Flag de especialização: MA de Parques.')),
            ],
            options={
                'verbose_name': 'meio de alimentação e bebidas',
                'verbose_name_plural': 'meios de alimentação e bebidas',
                'db_table': 'meio_alimentacao_bebida',
            },
            bases=('inventario.estabelecimento',),
        ),
        migrations.CreateModel(
            name='MeioHospedagem',
            fields=[
                ('estabelecimento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventario.estabelecimento')),
                ('aceita_pesquisas', models.BooleanField(default=False, help_text='Aceita participar das pesquisas mensais (ocupação).')),
                ('telefone_pesquisa', models.CharField(blank=True, max_length=20)),
                ('email_pesquisa', models.EmailField(blank=True, max_length=254)),
                ('data_abertura', models.DateField(blank=True, null=True)),
                ('inventario', models.TextField(blank=True)),
                ('uh_total', models.PositiveIntegerField(blank=True, null=True, verbose_name='UHs (total)')),
                ('uh_pcd', models.PositiveIntegerField(blank=True, null=True, verbose_name='UHs PCD')),
                ('leitos', models.PositiveIntegerField(blank=True, null=True)),
                ('funcionamento_24h', models.BooleanField(default=False)),
                ('horario_checkin', models.TimeField(blank=True, null=True)),
                ('horario_checkout', models.TimeField(blank=True, null=True)),
                ('reservas', models.CharField(blank=True, help_text='Como reservar (canal/observações).', max_length=255)),
            ],
            options={
                'verbose_name': 'meio de hospedagem',
                'verbose_name_plural': 'meios de hospedagem',
                'db_table': 'meio_hospedagem',
            },
            bases=('inventario.estabelecimento',),
        ),
        migrations.CreateModel(
            name='OrganizadorServicoEvento',
            fields=[
                ('estabelecimento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventario.estabelecimento')),
                ('atuacao', models.CharField(blank=True, choices=[('organizador', 'Organizador de Evento'), ('servico', 'Serviço para Evento')], max_length=15)),
                ('destinos_inteligentes', models.BooleanField(default=False)),
                ('forma_atendimento', models.TextField(blank=True)),
                ('servicos_oferecidos', models.TextField(blank=True)),
                ('observacao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'organizador/serviço para eventos',
                'verbose_name_plural': 'organizadores/serviços para eventos',
                'db_table': 'organizador_servico_evento',
            },
            bases=('inventario.estabelecimento',),
        ),
        migrations.CreateModel(
            name='ServicoApoio',
            fields=[
                ('estabelecimento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventario.estabelecimento')),
                ('tipo_servico', models.CharField(choices=[('cabeleireiro_barbeiro', 'Cabeleireiro e Barbeiro'), ('clinica_odontologica', 'Clínica Odontológica'), ('clinica_medica', 'Clínica Médica'), ('clinica_veterinaria', 'Clínica Veterinária'), ('educacao', 'Educação'), ('farmacia', 'Farmácia e Drogaria'), ('lavanderia', 'Lavanderia'), ('posto_combustivel', 'Posto de Combustível'), ('mecanica', 'Serviços Automotivos (Mecânica)'), ('servico_seguranca', 'Serviço de Segurança'), ('supermercado', 'Supermercado')], max_length=30)),
                ('observacao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'serviço de apoio ao turista',
                'verbose_name_plural': 'serviços de apoio ao turista',
                'db_table': 'servico_apoio',
            },
            bases=('inventario.estabelecimento',),
        ),
        migrations.CreateModel(
            name='ServicoSaude',
            fields=[
                ('estabelecimento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventario.estabelecimento')),
                ('principais_servicos', models.TextField(blank=True)),
                ('outras_informacoes', models.TextField(blank=True)),
                ('horarios_emergencia', models.TextField(blank=True, verbose_name='Horários de atendimento de emergência')),
            ],
            options={
                'verbose_name': 'serviço de saúde',
                'verbose_name_plural': 'serviços de saúde',
                'db_table': 'servico_saude',
            },
            bases=('inventario.estabelecimento',),
        ),
        migrations.CreateModel(
            name='TemploReligioso',
            fields=[
                ('estabelecimento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventario.estabelecimento')),
                ('possibilidade_visitacao', models.BooleanField(default=False)),
                ('como_funciona', models.TextField(blank=True)),
                ('data_quermesse_eventos', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'templo religioso',
                'verbose_name_plural': 'templos religiosos',
                'db_table': 'templo_religioso',
            },
            bases=('inventario.estabelecimento',),
        ),
        migrations.CreateModel(
            name='ProdutoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('codigo', models.CharField(blank=True, max_length=60)),
                ('detalhes', models.TextField(blank=True)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_servicos', to='inventario.estabelecimento')),
            ],
            options={
                'verbose_name': 'produto/serviço',
                'verbose_name_plural': 'produtos/serviços',
                'db_table': 'produto_servico',
            },
        ),
        migrations.CreateModel(
            name='Medicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metrica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.caracteristicavalor')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.estabelecimento')),
            ],
            options={
                'verbose_name': 'medição',
                'verbose_name_plural': 'medições',
                'db_table': 'medicao',
            },
        ),
        migrations.CreateModel(
            name='EstabelecimentoCaracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caracteristica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.caracteristica')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.estabelecimento')),
            ],
            options={
                'verbose_name': 'característica do estabelecimento',
                'verbose_name_plural': 'características do estabelecimento',
                'db_table': 'estabelecimento_caracteristica',
            },
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='caracteristicas',
            field=models.ManyToManyField(blank=True, related_name='estabelecimentos', through='inventario.EstabelecimentoCaracteristica', to='inventario.caracteristica'),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='formas_pagamento',
            field=models.ManyToManyField(blank=True, related_name='estabelecimentos', to='inventario.pagamento'),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='metricas',
            field=models.ManyToManyField(blank=True, related_name='estabelecimentos', through='inventario.Medicao', to='inventario.caracteristicavalor'),
        ),
        migrations.CreateModel(
            name='GrupoFolclorico',
            fields=[
                ('registroinventario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventario.registroinventario')),
                ('nome', models.CharField(max_length=255)),
                ('razao_social', models.CharField(blank=True, max_length=255)),
                ('tipo_documento', models.CharField(choices=[('cpf', 'CPF'), ('cnpj', 'CNPJ')], max_length=4)),
                ('documento', models.CharField(max_length=14)),
                ('classificacao_grupo', models.CharField(blank=True, max_length=120)),
                ('quantidade', models.PositiveIntegerField(blank=True, null=True)),
                ('quantidade_participantes', models.PositiveIntegerField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'grupo folclórico/parafolclórico',
                'verbose_name_plural': 'grupos folclóricos/parafolclóricos',
                'db_table': 'grupo_folclorico',
                'constraints': [models.UniqueConstraint(fields=('tipo_documento', 'documento'), name='uq_grupo_folclorico_documento')],
            },
            bases=('inventario.registroinventario',),
        ),
        migrations.CreateModel(
            name='RedeSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Plataforma. Ex.: Instagram.', max_length=60)),
                ('perfil', models.CharField(help_text='@usuario ou URL do perfil.', max_length=255)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redes_sociais', to='inventario.registroinventario')),
            ],
            options={
                'verbose_name': 'rede social',
                'verbose_name_plural': 'redes sociais',
                'db_table': 'rede_social',
                'constraints': [models.UniqueConstraint(fields=('registro', 'nome', 'perfil'), name='uq_rede_social_registro_nome_perfil')],
            },
        ),
        migrations.CreateModel(
            name='RegistroODS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='inventario.indicadorods')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores_ods', to='inventario.registroinventario')),
            ],
            options={
                'verbose_name': 'ODS do registro',
                'verbose_name_plural': 'ODS dos registros',
                'db_table': 'registro_ods',
                'constraints': [models.UniqueConstraint(fields=('registro', 'indicador'), name='uq_registro_ods')],
            },
        ),
        migrations.CreateModel(
            name='EventoProgramado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('quantidade', models.PositiveIntegerField(blank=True, help_text='Público/quantidade estimada (planilha).', null=True)),
                ('data_realizacao', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True)),
                ('espaco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='inventario.espacoevento')),
            ],
            options={
                'verbose_name': 'evento programado',
                'verbose_name_plural': 'eventos programados',
                'db_table': 'evento_programado',
            },
        ),
        migrations.CreateModel(
            name='VinculoTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_trade', to=settings.AUTH_USER_MODEL)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis', to='inventario.estabelecimento')),
            ],
            options={
                'verbose_name': 'vínculo do trade',
                'verbose_name_plural': 'vínculos do trade',
                'db_table': 'vinculo_trade',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'estabelecimento'), name='uq_vinculo_trade')],
            },
        ),
        migrations.AddConstraint(
            model_name='medicao',
            constraint=models.UniqueConstraint(fields=('estabelecimento', 'metrica'), name='uq_medicao_estab_metrica'),
        ),
        migrations.AddConstraint(
            model_name='estabelecimentocaracteristica',
            constraint=models.UniqueConstraint(fields=('estabelecimento', 'caracteristica'), name='uq_estab_caracteristica'),
        ),
    ]
