# Generated by Django 6.0.6 on 2026-06-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', 'seed_caracteristicas'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroinventario',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Indica se o estabelecimento está ativo ou não no inventário.'),
        ),
    ]
