# Generated by Django 6.0.6 on 2026-06-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_registroinventario_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='qtde_funcionarios_fixos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Funcionários Fixos'),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='qtde_funcionarios_temporarios',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Funcionários Temporários'),
        ),
    ]
