# Generated by Django 6.0.6 on 2026-06-20 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_estabelecimento_qtde_funcionarios_fixos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escopo', models.CharField(choices=[('atrativos', 'Atrativos, Lazer e Entretenimento'), ('meio_hospedagem', 'Meios de Hospedagem'), ('alimentacao', 'Meios de Alimentação e Bebidas'), ('agencias', 'Agências e Operadoras de Turismo'), ('espacos_eventos', 'Espaços para Eventos'), ('organizadores', 'Organizadores e Serviços p/ Eventos'), ('artesanato', 'Artesanato e Comércio Diferenciado')], max_length=20)),
                ('nome', models.CharField(max_length=120)),
                ('com_pergunta', models.BooleanField(default=False)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'secao',
                'constraints': [models.UniqueConstraint(fields=('escopo', 'nome'), name='uq_secao_escopo_nome')],
            },
        ),
        migrations.AddField(
            model_name='caracteristica',
            name='secao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='caracteristicas', to='inventario.secao'),
        ),
    ]
