# Generated by Django 6.0.6 on 2026-06-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_fix_mapeamento_secoes_catalogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupofolclorico',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('cpf', 'CPF'), ('cnpj', 'CNPJ')], max_length=4),
        ),
    ]
