"""Catálogo de características de ACESSIBILIDADE (sem "Não"), por escopo.

Fonte única das características de acessibilidade dos 5 escopos. NÃO grava
seção (roda antes do campo existir); a vinculação à seção é feita pelos
seeds de seção (0004, 0005, 0007).

Sem linhas "Não" e sem o grupo "Acessibilidade (geral)": a ausência de
marcação já significa "não possui", e o portão Sim/Não é a propriedade
`com_pergunta` da seção — não uma opção do catálogo.

Total: 339 características em 5 escopos.
"""

from django.db import migrations

CARACTERISTICAS = {
    "meio_hospedagem": [
        ("Pessoal capacitado para receber pessoas com deficiência", "Física"),
        ("Pessoal capacitado para receber pessoas com deficiência", "Auditiva"),
        ("Pessoal capacitado para receber pessoas com deficiência", "Visual"),
        ("Pessoal capacitado para receber pessoas com deficiência", "Intelectual"),
        ("Pessoal capacitado para receber pessoas com deficiência", "Múltipla"),
        ("Rota externa acessível", "Calçada rebaixada"),
        ("Rota externa acessível", "Faixa de pedestre"),
        ("Rota externa acessível", "Rampa"),
        ("Rota externa acessível", "Semáforo Sonoro"),
        ("Rota externa acessível", "Piso tátil de alerta"),
        ("Rota externa acessível", "Piso regular e antiderrapante"),
        ("Rota externa acessível", "Livre de obstáculos"),
        ("Rota externa acessível", "Acesso em nível"),
        ("Local de embarque e desembarque", "Sinalizado"),
        ("Local de embarque e desembarque", "Com acesso em nível"),
        ("Local de embarque e desembarque", "Sem Obtáculos"),
        ("Local de embarque e desembarque", "Outras"),
        ("Vaga em estacionamento", "Sinalizada"),
        ("Vaga em estacionamento", "Com acesso em nível"),
        ("Vaga em estacionamento", "Alargada para cadeira de rodas"),
        ("Vaga em estacionamento", "Rampa de acesso à calçada"),
        ("Vaga em estacionamento", "Outras"),
        ("Área de circulação/acesso interno para cadeiras de rodas", "Plataforma elevatória"),
        ("Área de circulação/acesso interno para cadeiras de rodas", "Com circulação entre mobiliário"),
        ("Área de circulação/acesso interno para cadeiras de rodas", "Porta larga"),
        ("Área de circulação/acesso interno para cadeiras de rodas", "Outras"),
        ("Escada", "Corrimão"),
        ("Escada", "Patamar para descanso"),
        ("Escada", "Sinalização/Piso tátil de alerta"),
        ("Escada", "Sinalização visual"),
        ("Escada", "Piso antiderrapante"),
        ("Escada", "Outros"),
        ("Rampa", "Corrimão"),
        ("Rampa", "Patamar para descanso"),
        ("Rampa", "Piso antiderrapante"),
        ("Rampa", "Sinalização / piso tátil"),
        ("Rampa", "Inclinação adequada"),
        ("Piso", "Tátil"),
        ("Piso", "Regular, sem obstáculos (tapete ou desnível)"),
        ("Piso", "Antiderrapante/deslizante"),
        ("Elevador", "Sinalizado em Braille"),
        ("Elevador", "Dispositivo sonoro"),
        ("Elevador", "Dispositivo luminoso"),
        ("Elevador", "Sensor eletrônico (porta)"),
        ("Elevador", "Sinalização visual"),
        ("Elevador", "Outros"),
        ("Equipamento motorizado para deslocamento interno", "Sim"),
        ("Sinalização visual", "Entrada / Saída"),
        ("Sinalização visual", "Recepção"),
        ("Sinalização visual", "Sanitário"),
        ("Sinalização visual", "Eventos"),
        ("Sinalização visual", "Restaurante"),
        ("Sinalização visual", "Área de lazer"),
        ("Sinalização visual", "Área de resgate"),
        ("Alarme de emergência", "Sim"),
        ("Comunicação", "Texto informativo em Braille"),
        ("Comunicação", "Texto informativo em fonte ampliada"),
        ("Comunicação", "Intérprete em Libras (língua brasileira de sinais)"),
        ("Balcão de atendimento", "Rebaixado"),
        ("Balcão de atendimento", "Preferencial para pessoas com deficiência ou mobilidade reduzida"),
        ("Mobiliário", "Altura adequada"),
        ("Mobiliário", "Recuo adequado"),
        ("Sanitário", "Barra de apoio"),
        ("Sanitário", "Porta larga suficiente para entrada de cadeira de rodas"),
        ("Sanitário", "Acesso e giro para cadeira de rodas"),
        ("Sanitário", "Pia rebaixada"),
        ("Sanitário", "Espelho rebaixado ou com ângulo de alcance visual"),
        ("Sanitário", "Box ou banheira adaptada"),
        ("Sanitário", "Torneira monocomando/alavanca"),
        ("Sanitário", "Piso regular, sem obstáculos"),
        ("Sanitário", "Piso tátil"),
        ("Sanitário", "Outros"),
        ("Telefone", "Altura adequada"),
        ("Telefone", "Para surdos (TPS ou TTS)"),
        ("Sinalização indicativa de atendimento preferencial para PCD", "Sim"),
    ],
    "alimentacao": [
        ("Capacidade para receber pessoas com deficiência", "Física"),
        ("Capacidade para receber pessoas com deficiência", "Auditiva"),
        ("Capacidade para receber pessoas com deficiência", "Visual"),
        ("Capacidade para receber pessoas com deficiência", "Intelectual"),
        ("Capacidade para receber pessoas com deficiência", "Múltipla"),
        ("Rota externa acessível", "Calçada rebaixada"),
        ("Rota externa acessível", "Faixa de pedestre"),
        ("Rota externa acessível", "Rampa"),
        ("Rota externa acessível", "Semáforo sonoro"),
        ("Rota externa acessível", "Piso regular/anti derrapante"),
        ("Rota externa acessível", "Livre de obstáculos"),
        ("Rota externa acessível", "Outras"),
        ("Local de embarque e desembarque", "Sinalizado"),
        ("Local de embarque e desembarque", "Com acesso em nível"),
        ("Estacionamento", "Sinalizada"),
        ("Estacionamento", "Com acesso em nível"),
        ("Estacionamento", "Alargada para cadeira de rodas"),
        ("Estacionamento", "Rampa de acesso à calçada"),
        ("Área de circulação/acesso interno para cadeiras de rodas", "Plataforma elevatória"),
        ("Área de circulação/acesso interno para cadeiras de rodas", "Com circulação entre mobiliário"),
        ("Área de circulação/acesso interno para cadeiras de rodas", "Porta larga"),
        ("Escada", "Corrimão"),
        ("Escada", "Patamar para descanso"),
        ("Escada", "Sinalização tátil de alerta"),
        ("Escada", "Piso antiderrapante"),
        ("Escada", "Piso tátil"),
        ("Escada", "Outros"),
        ("Rampa", "Corrimão"),
        ("Rampa", "Patamar para descanso"),
        ("Rampa", "Piso antiderrapante"),
        ("Rampa", "Sinalização tátil"),
        ("Rampa", "Piso tátil"),
        ("Rampa", "Inclinação adequada"),
        ("Rampa", "Outros"),
        ("Piso", "Tátil"),
        ("Piso", "Sem obstáculos (tapete ou desnível)"),
        ("Piso", "Antiderrapante/antideslizante"),
        ("Elevador", "Sinalizado em Braille"),
        ("Elevador", "Dispositivo sonoro"),
        ("Elevador", "Dispositivo luminoso"),
        ("Elevador", "Sensor eletrônico (porta)"),
        ("Elevador", "Outros"),
        ("Equipamento motorizado para deslocamento interno", "Sim"),
        ("Sinalização visual", "Atendimento Prefrencial Pcd"),
        ("Sinalização visual", "Entrada/Saída"),
        ("Sinalização visual", "Caixa"),
        ("Sinalização visual", "Sanitário"),
        ("Sinalização visual", "Sanitário PCD"),
        ("Sinalização visual", "Elevador"),
        ("Sinalização visual", "Escada"),
        ("Sinalização visual", "Cozinha"),
        ("Sinalização visual", "Área de lazer"),
        ("Sinalização visual", "Área de resgate"),
        ("Alarme de emergência para deficientes", "Sim"),
        ("Comunicação", "Cardápio em Braille"),
        ("Comunicação", "Cardápio em língua estrangeira"),
        ("Comunicação", "Cardápio em fonte ampliada"),
        ("Comunicação", "Telefone para surdos (TPS ou TTS)"),
        ("Comunicação", "Intérprete em Libras (língua brasileira de sinais)"),
        ("Balcão de atendimento", "Rebaixado"),
        ("Mobiliário", "Altura adequada"),
        ("Mobiliário", "Recuo adequado"),
        ("Sanitário", "Barra de apoio"),
        ("Sanitário", "Porta larga suficiente para entrada de cadeira de rodas"),
        ("Sanitário", "Giro para cadeira de rodas"),
        ("Sanitário", "Acesso para cadeira de rodas"),
        ("Sanitário", "Pia rebaixada"),
        ("Sanitário", "Espelho rebaixado ou com ângulo de alcance visual"),
        ("Sanitário", "Torneira monocomando/alavanca"),
        ("Sanitário", "Outros"),
    ],
    "atrativos": [
        ("Pessoal capacitado para receber pessoas com deficiência", "Física"),
        ("Pessoal capacitado para receber pessoas com deficiência", "Auditiva"),
        ("Pessoal capacitado para receber pessoas com deficiência", "Visual"),
        ("Pessoal capacitado para receber pessoas com deficiência", "Intelectual"),
        ("Pessoal capacitado para receber pessoas com deficiência", "Múltipla"),
        ("Rota externa acessível", "Calçada rebaixada"),
        ("Rota externa acessível", "Faixa de pedestre"),
        ("Rota externa acessível", "Rampa"),
        ("Rota externa acessível", "Semáforo sonoro"),
        ("Rota externa acessível", "Piso tátil de alerta"),
        ("Rota externa acessível", "Piso regular e antiderrapante"),
        ("Rota externa acessível", "Livre de obstáculos"),
        ("Rota externa acessível", "Acesso em Nível"),
        ("Local de embarque e desembarque", "Sinalizado"),
        ("Local de embarque e desembarque", "Com acesso em nível"),
        ("Local de embarque e desembarque", "Sem obstáculos"),
        ("Local de embarque e desembarque", "Rampa de acesso à calçada"),
        ("Vaga de Estacionamento", "Sinalizada"),
        ("Vaga de Estacionamento", "Com acesso em nível"),
        ("Vaga de Estacionamento", "Alargada para cadeira de rodas"),
        ("Vaga de Estacionamento", "Rampa de acesso à calçada"),
        ("Área de circulação/acesso interno para cadeiras de rodas", "Plataforma elevatória"),
        ("Área de circulação/acesso interno para cadeiras de rodas", "Com circulação entre mobiliário"),
        ("Área de circulação/acesso interno para cadeiras de rodas", "Porta larga"),
        ("Área de circulação/acesso interno para cadeiras de rodas", "Saídas de Emergência"),
        ("Área de circulação/acesso interno para cadeiras de rodas", "Outros"),
        ("Escadas", "Corrimão"),
        ("Escadas", "Patamar para descanso"),
        ("Escadas", "Sinalização/piso tátil de alerta"),
        ("Escadas", "Piso antiderrapante"),
        ("Escadas", "Sinalização Visual"),
        ("Escadas", "Outros"),
        ("Rampa", "Corrimão"),
        ("Rampa", "Patamar para descanso"),
        ("Rampa", "Piso antiderrapante"),
        ("Rampa", "Sinalização tátil"),
        ("Rampa", "Inclinação adequada"),
        ("Piso", "Tátil"),
        ("Piso", "Sem obstáculos (tapete ou desnível)"),
        ("Piso", "Antiderrapante/deslizante"),
        ("Elevador", "Sinalizado em Braille"),
        ("Elevador", "Dispositivo sonoro"),
        ("Elevador", "Dispositivo luminoso"),
        ("Elevador", "Sensor eletrônico (porta)"),
        ("Elevador", "Sinalização Visual"),
        ("Elevador", "Outros"),
        ("Equipamento motorizado ou não para deslocamento interno", "Sim"),
        ("Sinalização visual", "Entrada/Saída"),
        ("Sinalização visual", "Recepção/Caixa"),
        ("Sinalização visual", "Saída de Emergência/Equip. Incêndio"),
        ("Sinalização visual", "Sanitário"),
        ("Sinalização visual", "Área de Alimentação"),
        ("Sinalização visual", "Ambulatório"),
        ("Sinalização visual", "Área de resgate"),
        ("Alarme de Emergência para PCD", "Sim"),
        ("Comunicação", "Texto informativo em Braille"),
        ("Comunicação", "Texto informativo em fonte ampliada"),
        ("Comunicação", "Intérprete em Libras (língua brasileira de sinais)"),
        ("Balcão de Atendimento", "Rebaixado"),
        ("Balcão de Atendimento", "Preferencial para pessoas com deficiência ou mobilidade reduzida"),
        ("Mobiliário", "Altura adequada"),
        ("Mobiliário", "Recuo adequado"),
        ("Sanitário", "Barra de apoio"),
        ("Sanitário", "Porta larga suficiente para entrada de cadeira de rodas"),
        ("Sanitário", "Acesso e giro para cadeira de rodas"),
        ("Sanitário", "Pia rebaixada"),
        ("Sanitário", "Espelho rebaixado ou com ângulo de alcance visual"),
        ("Sanitário", "Box ou banheira adaptada"),
        ("Sanitário", "Torneira monocomando/alavanca"),
        ("Sanitário", "Piso regular, sem obstáculos"),
        ("Sanitário", "Piso Tátil"),
        ("Sanitário", "Outros"),
        ("Telefone", "Altura adequada"),
        ("Telefone", "Para surdos (TPS ou TTS)"),
        ("Sinalização indicativa de atendimento preferencial para PCD", "Sim"),
    ],
    "espacos_eventos": [
        ("MOBILIÁRIO PCD", "Altura adequada"),
        ("MOBILIÁRIO PCD", "Recuo adequado"),
        ("ÁREA INTERNA", "Porta larga"),
        ("ÁREA INTERNA", "Piso regular"),
        ("ÁREA INTERNA", "Piso antiderrapante"),
        ("ÁREA INTERNA", "Piso sem obstáculos"),
        ("ÁREA INTERNA", "Equip. Motorizado ou não (cadeira de rodas)"),
        ("ÁREA INTERNA", "Balcão de Atendimento rebaixadopara PCD"),
        ("ÁREA INTERNA", "Locais demarcados para PCD"),
        ("ÁREA INTERNA", "Textos em fontes ampliadas"),
        ("ÁREA INTERNA", "Textos em Braile"),
        ("ÁREA INTERNA", "Telefone para surdos"),
        ("ÁREA INTERNA", "Intéprete em Libras"),
        ("ÁREA INTERNA", "Plataforma elevatória"),
        ("ELEVADOR", "Dispositivo Sonoro"),
        ("ELEVADOR", "Dispositivo Luminoso"),
        ("ELEVADOR", "Sinalizado em braile"),
        ("ELEVADOR", "sensor eletrônico nas portas"),
        ("ELEVADOR", "Sinalização visual"),
        ("ELEVADOR", "outro"),
        ("ESCADA", "Corrimão"),
        ("ESCADA", "Patamar para descando"),
        ("ESCADA", "Sinalização visual"),
        ("ESCADA", "Piso aniderrapante"),
        ("ESCADA", "Outro"),
        ("RAMPA", "Corrimão"),
        ("RAMPA", "Patamar para descando"),
        ("RAMPA", "inclinação adequada"),
        ("RAMPA", "Sinalização visual"),
        ("RAMPA", "Piso aniderrapante"),
        ("RAMPA", "Outro"),
        ("INSTALAÇÕES SANITÁRIAS", "Feminino"),
        ("INSTALAÇÕES SANITÁRIAS", "Masculino"),
        ("INSTALAÇÕES SANITÁRIAS", "Serviço"),
        ("INSTALAÇÕES SANITÁRIAS", "PCD"),
        ("INSTALAÇÕES SANITÁRIAS", "Barras de Apoio"),
        ("INSTALAÇÕES SANITÁRIAS", "Porta Larga"),
        ("INSTALAÇÕES SANITÁRIAS", "Espaço para giro"),
        ("INSTALAÇÕES SANITÁRIAS", "Pia rebaixada"),
        ("INSTALAÇÕES SANITÁRIAS", "Espelho rebaixado"),
        ("INSTALAÇÕES SANITÁRIAS", "Vaso sanitário adaptado"),
        ("INSTALAÇÕES SANITÁRIAS", "Box/Banheira adaptada"),
        ("INSTALAÇÕES SANITÁRIAS", "Torneira monocomando/alavanca"),
        ("INSTALAÇÕES SANITÁRIAS", "Piso regular"),
        ("INSTALAÇÕES SANITÁRIAS", "Alarme de emergência PCD"),
        ("INSTALAÇÕES SANITÁRIAS", "Outros"),
        ("EQUPAMENTOS E SERVIÇOS", "Aparelho de scanner"),
        ("EQUPAMENTOS E SERVIÇOS", "Apontador laser pointer"),
        ("EQUPAMENTOS E SERVIÇOS", "Ar condicionado"),
        ("EQUPAMENTOS E SERVIÇOS", "Bancados"),
        ("EQUPAMENTOS E SERVIÇOS", "Bandeiras"),
        ("EQUPAMENTOS E SERVIÇOS", "Camarins"),
        ("EQUPAMENTOS E SERVIÇOS", "Circuito interno de TV"),
        ("EQUPAMENTOS E SERVIÇOS", "Climatização"),
        ("EQUPAMENTOS E SERVIÇOS", "Computador"),
        ("EQUPAMENTOS E SERVIÇOS", "Equipamento de tradução simultânea"),
        ("EQUPAMENTOS E SERVIÇOS", "Flip Chart"),
        ("EQUPAMENTOS E SERVIÇOS", "Impressora"),
        ("EQUPAMENTOS E SERVIÇOS", "Internet/Wi-fi"),
        ("EQUPAMENTOS E SERVIÇOS", "Manobrista"),
        ("EQUPAMENTOS E SERVIÇOS", "Máquina copiadora"),
        ("EQUPAMENTOS E SERVIÇOS", "Montagem de estandes"),
        ("EQUPAMENTOS E SERVIÇOS", "Palco"),
        ("EQUPAMENTOS E SERVIÇOS", "Pulpito"),
        ("EQUPAMENTOS E SERVIÇOS", "Projetor multimídea"),
        ("EQUPAMENTOS E SERVIÇOS", "Quadro/lousa"),
        ("EQUPAMENTOS E SERVIÇOS", "Serviço de copa/café"),
        ("EQUPAMENTOS E SERVIÇOS", "Serviço de limpeza"),
        ("EQUPAMENTOS E SERVIÇOS", "Serviço de manobrista"),
        ("EQUPAMENTOS E SERVIÇOS", "Serviço de garçons / atendentes"),
        ("EQUPAMENTOS E SERVIÇOS", "Serviço de recepcionista"),
        ("EQUPAMENTOS E SERVIÇOS", "Serviço de segurança"),
        ("EQUPAMENTOS E SERVIÇOS", "Sonorização"),
        ("EQUPAMENTOS E SERVIÇOS", "Tablado"),
        ("EQUPAMENTOS E SERVIÇOS", "Tela de projeção"),
        ("EQUPAMENTOS E SERVIÇOS", "Tela fixa"),
        ("EQUPAMENTOS E SERVIÇOS", "Tela móvel"),
        ("EQUPAMENTOS E SERVIÇOS", "Telefonia"),
        ("EQUPAMENTOS E SERVIÇOS", "TV"),
        ("EQUPAMENTOS E SERVIÇOS", "Outros"),
        ("SERVIÇOS E ITENS DE SEGURANÇA", "Ambulatório"),
        ("SERVIÇOS E ITENS DE SEGURANÇA", "Detector de metais"),
        ("SERVIÇOS E ITENS DE SEGURANÇA", "Alarme e equipamentos de incêndio"),
        ("SERVIÇOS E ITENS DE SEGURANÇA", "Área de resgate"),
        ("SERVIÇOS E ITENS DE SEGURANÇA", "Saída de Emergência"),
        ("SERVIÇOS E ITENS DE SEGURANÇA", "Placas de sinalização de espaços"),
        ("SERVIÇOS E ITENS DE SEGURANÇA", "Sinalização de atendimento prioritário"),
        ("SERVIÇOS E ITENS DE SEGURANÇA", "Guarda volumes"),
        ("SERVIÇOS E ITENS DE SEGURANÇA", "achados e perdidos"),
        ("SERVIÇOS E ITENS DE SEGURANÇA", "Outros"),
        ("ENERGIA ELÉTRICA", "110 volts"),
        ("ENERGIA ELÉTRICA", "220 volts"),
        ("ENERGIA ELÉTRICA", "110/220 volts"),
        ("ENERGIA ELÉTRICA", "Capacidade em KVA"),
        ("GERADOR DE EMERGÊNCIA", "Sim"),
        ("GERADOR DE EMERGÊNCIA", "Capacidade em KVA"),
        ("GERADOR DE EMERGÊNCIA", "INVENTÁRIO"),
    ],
    "agencias": [
        ("PESSOAL CAPACITADO PARA ATENDER PESSOAS COM DEFICIÊNCIA", "Física"),
        ("PESSOAL CAPACITADO PARA ATENDER PESSOAS COM DEFICIÊNCIA", "Auditiva"),
        ("PESSOAL CAPACITADO PARA ATENDER PESSOAS COM DEFICIÊNCIA", "Visual"),
        ("PESSOAL CAPACITADO PARA ATENDER PESSOAS COM DEFICIÊNCIA", "Intelectual"),
        ("PESSOAL CAPACITADO PARA ATENDER PESSOAS COM DEFICIÊNCIA", "Múltipla"),
        ("ACESSIBILIDADE", "Calçada Rebaixada"),
        ("ACESSIBILIDADE", "Vaga demarcada para PCD"),
        ("ACESSIBILIDADE", "Faixa de Pedestre"),
        ("ACESSIBILIDADE", "Rampa de Acesso"),
        ("ACESSIBILIDADE", "Telefone para Surdos (TPS ou TTS)"),
        ("ACESSIBILIDADE", "Texto em Braile"),
        ("ACESSIBILIDADE", "Texto em fonte ampliada"),
        ("ACESSIBILIDADE", "Intérprete de Libras"),
        ("ACESSIBILIDADE", "Balcão rebaixado"),
        ("ACESSIBILIDADE", "Mobiliário com altura e recúo adequado"),
        ("ACESSIBILIDADE", "Instalações Sanitárias para PCD"),
        ("ACESSIBILIDADE", "Espaço Sensorial"),
        ("ACESSIBILIDADE", "Espaço interno para circulação de cadeira de roda"),
        ("ACESSIBILIDADE", "Elevador/Plataforma Elevatória"),
        ("ACESSIBILIDADE", "Piso regular, sem obstáculos"),
        ("ACESSIBILIDADE", "Outro:"),
        ("ACESSIBILIDADE", "OBSERVAÇÃO"),
    ],
}


def semear(apps, schema_editor):
    Caracteristica = apps.get_model("inventario", "Caracteristica")
    objs = [
        Caracteristica(escopo=esc, nome=g, categoria=o, customizada=False)
        for esc, pares in CARACTERISTICAS.items() for (g, o) in pares
    ]
    Caracteristica.objects.bulk_create(objs, ignore_conflicts=True)


def remover(apps, schema_editor):
    Caracteristica = apps.get_model("inventario", "Caracteristica")
    for esc, pares in CARACTERISTICAS.items():
        for g, o in pares:
            Caracteristica.objects.filter(escopo=esc, nome=g, categoria=o, customizada=False).delete()


class Migration(migrations.Migration):
    dependencies = [("inventario", "0001_initial")]
    operations = [migrations.RunPython(semear, remover)]