# Generated by Django 6.0.6 on 2026-06-20 19:21

import django.core.validators
import django.db.models.deletion
import historico.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Planejamento 2026', max_length=120, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'pasta',
                'verbose_name_plural': 'pastas',
                'db_table': 'pasta',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TagSegmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'tag de segmento',
                'verbose_name_plural': 'tags de segmento',
                'db_table': 'tag_segmento',
            },
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: Projeção Carnaval 2026', max_length=255)),
                ('quantidade_registros', models.PositiveIntegerField(blank=True, help_text='Opcional. Preenchido se vier do cruzamento de dados.', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('pasta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios', to='historico.pasta')),
                ('tags', models.ManyToManyField(blank=True, related_name='relatorios', to='historico.tagsegmento')),
            ],
            options={
                'verbose_name': 'relatório / busca salva',
                'verbose_name_plural': 'relatórios / buscas salvas',
                'db_table': 'relatorio',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ArquivoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=historico.models.diretorio_upload_arquivos)),
                ('nome_original', models.CharField(help_text='Nome real do arquivo enviado', max_length=255)),
                ('tamanho_kb', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='historico.relatorio')),
            ],
            options={
                'verbose_name': 'arquivo anexo',
                'verbose_name_plural': 'arquivos anexos',
                'db_table': 'arquivo_anexo',
            },
        ),
    ]
