# Generated by Django 6.0.6 on 2026-06-23 15:52

import django.db.models.deletion
import historico.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoImportacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=historico.models.diretorio_upload_importacao)),
                ('nome', models.CharField(max_length=255)),
                ('fonte', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('processado', 'Processado'), ('falhou', 'Falhou')], default='processado', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_importacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'histórico de importação',
                'verbose_name_plural': 'históricos de importação',
                'db_table': 'historico_importacao',
                'ordering': ['-criado_em', '-id'],
            },
        ),
    ]
